name: La Frikitiva
url: http://lafrikitiva.com
description: GRAZIAS DE HENTREKOTT

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
